version: "3"

networks:
    loki:

services:
  amazing_wiki:
    build: ./
    image: amazing_wiki
    container_name: amazing_wiki

    privileged: false
    restart: always
    ports:
    - 8181:8181
    volumes:
    - ./conf/:/conf
    - ./database/:/database
    - ./uploads/:/uploads
    environment:
    - AMAZING_RUN_MODE=prod
    - AMAZING_DB_ADAPTER=mysql
    - AMAZING_DB_DATABASE=amazing_wiki
    - AMAZING_DB_HOST=host.docker.internal
    - AMAZING_DB_PASSWORD= 
    - AMAZING_CACHE=true
    - AMAZING_CACHE_PROVIDER=file
    - AMAZING_ENABLE_EXPORT=false
    - AMAZING_BASE_URL=
    - AMAZING_CDN_IMG_URL=
    - AMAZING_CDN_CSS_URL=
    - AMAZING_CDN_JS_URL=
  networks:
      - loki
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/api/prom/push
        loki-retries: "5"
        loki-batch-size: "400"

  depends_on:
      - "loki"
      - "grafana"

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./conf/:/etc/loki
      - ./data/loki/:/tmp/loki
    command: -config.file=/etc/loki/loki-local-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
        - "3000:3000"
    user: "472"
    environment:
      GF_EXPLORE_ENABLED: "true"
    networks:
      - loki
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/api/prom/push
        loki-retries: "5"
        loki-batch-size: "400"


