version: "3"

services:
  amazing_wiki:
    image: hellodudu86/amazing_wiki
    container_name: amazing_wiki
    #command: install

    privileged: false
    restart: always
    ports:
        - 80:80
    volumes:
        - ./conf/:/app/conf
        - ./data/:/app/data
        - ./static/:/app/static
        - ./views/:/app/views
    environment:
        - AMAZING_RUN_MODE=dev
        - AMAZING_DB_USERNAME=root
        - AMAZING_DB_ADAPTER=mysql
        - AMAZING_DB_DATABASE=amazing_wiki
        - AMAZING_DB_HOST=mysql
        - AMAZING_DB_PORT=3306
        - AMAZING_DB_PASSWORD=123456 
        - AMAZING_CACHE=true
        - AMAZING_CACHE_PROVIDER=file
        - AMAZING_ENABLE_EXPORT=false
        - AMAZING_BASE_URL=
        - AMAZING_CDN_IMG_URL=
        - AMAZING_CDN_CSS_URL=
        - AMAZING_CDN_JS_URL=
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/api/prom/push
        loki-retries: "5"
        loki-batch-size: "400"

    depends_on:
      - "loki"
      - "grafana"
      - "mysql"

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./conf/:/etc/loki
      - ./data/loki/:/tmp/loki
    command: -config.file=/etc/loki/loki-local-config.yaml

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
        - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini
        - ./data/grafana/:/var/lib/grafana/
    ports:
        - "3000:3000"
    user: "472"
    environment:
      GF_EXPLORE_ENABLED: "true"
    #logging:
      #driver: loki
      #options:
        #loki-url: http://host.docker.internal:3100/api/prom/push
        #loki-retries: "5"
        #loki-batch-size: "400"

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
        - ./conf/promtail/:/etc/promtail
        - ./var/log:/var/log
    command:
        -config.file=/etc/promtail/promtail-docker-config.yaml
    ports:
        - "9080:9080"

  loki_conn:
    image: hellodudu86/loki_conn
    container_name: loki_conn
    command:
        -url="http://loki:3100/api/prom/push"
    depends_on:
        - loki

  loki_conn:
    image: hellodudu86/loki_conn
    container_name: loki_conn
    command:
        -url="http://loki:3100/api/prom/push"
    depends_on:
        - loki

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'amazing_wiki'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - ./data/database/:/var/lib/mysql
      - ./backup/:/backup
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/api/prom/push
        loki-retries: "5"
        loki-batch-size: "400"

